# Manually inspecting if the time range of ZBJBD does not match the seizures

In [5]:
import os
import numpy as np
import pandas as pd
from scipy.io import loadmat
from datetime import datetime, timedelta
from pathlib import Path
path = "//home/tperezsanchez/FoundationModel_EEG_Dissertation/Main_project/data/Working/ZBJBD/"
folder_path = Path(path)
all_files = os.listdir(folder_path)

print("Total files in folder:", len(all_files))

for f in all_files[:20]:
    print(f)

Total files in folder: 717
ZBJBD_300.mat
._ZBJBD_324.mat
._ZBJBD_7.mat
ZBJBD_25.mat
ZBJBD_104.mat
ZBJBD_22.mat
ZBJBD_74.mat
ZBJBD_297.mat
ZBJBD_69.mat
._ZBJBD_317.mat
ZBJBD_79.mat
ZBJBD_49.mat
ZBJBD_356.mat
ZBJBD_119.mat
ZBJBD_110.mat
._ZBJBD_70.mat
ZBJBD_269.mat
._ZBJBD_335.mat
._ZBJBD_286.mat
ZBJBD_57.mat

In [6]:
mat_files = sorted([
    f for f in all_files 
    if f.lower().endswith(".mat") and not f.startswith(".")
])

In [7]:
mat_files = sorted([
    f for f in all_files
    if f.lower().endswith(".mat") and not f.startswith(".")
])

print("Number of .mat files:", len(mat_files))

for i, f in enumerate(mat_files[:20]):
    print(i, f)

Number of .mat files: 357
0 ZBJBD_1.mat
1 ZBJBD_10.mat
2 ZBJBD_100.mat
3 ZBJBD_101.mat
4 ZBJBD_102.mat
5 ZBJBD_103.mat
6 ZBJBD_104.mat
7 ZBJBD_105.mat
8 ZBJBD_106.mat
9 ZBJBD_107.mat
10 ZBJBD_108.mat
11 ZBJBD_109.mat
12 ZBJBD_11.mat
13 ZBJBD_110.mat
14 ZBJBD_111.mat
15 ZBJBD_112.mat
16 ZBJBD_113.mat
17 ZBJBD_114.mat
18 ZBJBD_115.mat
19 ZBJBD_116.mat

In [8]:
idx = 0

filename = mat_files[idx]
file_path = folder_path / filename

print("Selected file:")
print(filename)
print(file_path)

Selected file:
ZBJBD_1.mat
//home/tperezsanchez/FoundationModel_EEG_Dissertation/Main_project/data/Working/ZBJBD/ZBJBD_1.mat

In [9]:
data_mat = loadmat(file_path)

print("Loaded file:", filename)
print("Available keys:")

for key in data_mat.keys():
    print(key)

Loaded file: ZBJBD_1.mat
Available keys:
__header__
__version__
__globals__
hdr
data

In [10]:
print("Type of hdr:", type(data_mat["hdr"]))
print("Shape of hdr:", data_mat["hdr"].shape)
print("Dtype of hdr:", data_mat["hdr"].dtype)

print("\nType of data:", type(data_mat["data"]))
print("Shape of data:", data_mat["data"].shape)
print("Dtype of data:", data_mat["data"].dtype)

Type of hdr: <class 'numpy.ndarray'>
Shape of hdr: (1, 1)
Dtype of hdr: [('Fs', 'O'), ('nChans', 'O'), ('label', 'O'), ('nSamples', 'O'), ('nSamplesPre', 'O'), ('nTrials', 'O'), ('orig', 'O'), ('chantype', 'O'), ('chanunit', 'O')]

Type of data: <class 'numpy.ndarray'>
Shape of data: (2, 4480308)
Dtype of data: float64

In [11]:
hdr = data_mat["hdr"]

print(type(hdr))
print(hdr.shape)
print(hdr.dtype)

<class 'numpy.ndarray'>
(1, 1)
[('Fs', 'O'), ('nChans', 'O'), ('label', 'O'), ('nSamples', 'O'), ('nSamplesPre', 'O'), ('nTrials', 'O'), ('orig', 'O'), ('chantype', 'O'), ('chanunit', 'O')]

In [12]:
print("Fields inside hdr:")

for field in hdr.dtype.names:
    print(field)

Fields inside hdr:
Fs
nChans
label
nSamples
nSamplesPre
nTrials
orig
chantype
chanunit

In [13]:
hdr["orig"][0, 0]["T0"][0, 0][0]

array([2021,    1,   13,   11,   40,   57], dtype=uint16)

In [14]:
orig = hdr["orig"]

print("orig type:", type(orig))
print("orig shape:", orig.shape)
print("orig dtype:", orig.dtype)

orig type: <class 'numpy.ndarray'>
orig shape: (1, 1)
orig dtype: object

In [15]:
orig_00 = orig[0, 0]

print("orig_00 type:", type(orig_00))
print("orig_00 shape:", getattr(orig_00, "shape", None))
print("orig_00 dtype:", getattr(orig_00, "dtype", None))

orig_00 type: <class 'numpy.ndarray'>
orig_00 shape: (1, 1)
orig_00 dtype: [('VERSION', 'O'), ('T0', 'O'), ('HeadLen', 'O'), ('NRec', 'O'), ('Dur', 'O'), ('NS', 'O'), ('Label', 'O'), ('Transducer', 'O'), ('PhysDim', 'O'), ('PhysMin', 'O'), ('PhysMax', 'O'), ('DigMin', 'O'), ('DigMax', 'O'), ('PreFilt', 'O'), ('SPR', 'O'), ('Cal', 'O'), ('Off', 'O'), ('Calib', 'O'), ('SampleRate', 'O'), ('Chan_Select', 'O'), ('ChanTyp', 'O'), ('AS', 'O'), ('chansel', 'O'), ('annotation', 'O')]

In [16]:
t0_raw = hdr["orig"][0, 0]["T0"][0, 0][0]

In [17]:
t0_level_1 = hdr["orig"]
print("Level 1:", type(t0_level_1), t0_level_1.shape)

t0_level_2 = t0_level_1[0, 0]
print("Level 2:", type(t0_level_2), t0_level_2.shape, t0_level_2.dtype)

t0_level_3 = t0_level_2["T0"]
print("Level 3:", type(t0_level_3), t0_level_3.shape, t0_level_3.dtype)

t0_level_4 = t0_level_3[0, 0]
print("Level 4:", type(t0_level_4), t0_level_4.shape, t0_level_4.dtype)

t0_raw = t0_level_4[0]
print("t0_raw:", t0_raw)
print("type:", type(t0_raw))
print("shape:", getattr(t0_raw, "shape", None))

Level 1: <class 'numpy.ndarray'> (1, 1)
Level 2: <class 'numpy.ndarray'> (1, 1) [('VERSION', 'O'), ('T0', 'O'), ('HeadLen', 'O'), ('NRec', 'O'), ('Dur', 'O'), ('NS', 'O'), ('Label', 'O'), ('Transducer', 'O'), ('PhysDim', 'O'), ('PhysMin', 'O'), ('PhysMax', 'O'), ('DigMin', 'O'), ('DigMax', 'O'), ('PreFilt', 'O'), ('SPR', 'O'), ('Cal', 'O'), ('Off', 'O'), ('Calib', 'O'), ('SampleRate', 'O'), ('Chan_Select', 'O'), ('ChanTyp', 'O'), ('AS', 'O'), ('chansel', 'O'), ('annotation', 'O')]
Level 3: <class 'numpy.ndarray'> (1, 1) object
Level 4: <class 'numpy.ndarray'> (1, 6) uint16
t0_raw: [2021    1   13   11   40   57]
type: <class 'numpy.ndarray'>
shape: (6,)

In [18]:
t0_dt = datetime(
    int(t0_raw[0]), int(t0_raw[1]), int(t0_raw[2]),
    int(t0_raw[3]), int(t0_raw[4]), int(t0_raw[5])
)

In [19]:
year = int(t0_raw[0])
month = int(t0_raw[1])
day = int(t0_raw[2])
hour = int(t0_raw[3])
minute = int(t0_raw[4])
second = int(t0_raw[5])

print(year, month, day, hour, minute, second)

2021 1 13 11 40 57

In [20]:
fs = float(hdr["Fs"][0, 0].item())

## print all T0 and check time ranges

In [21]:
mat_files = sorted([
    f for f in os.listdir(folder_path)
    if f.lower().endswith(".mat") and not f.startswith(".")
])

print("Number of .mat files:", len(mat_files))

Number of .mat files: 357

In [22]:
t0_results = []
errors = []

for i, filename in enumerate(mat_files):
    file_path = folder_path / filename

    try:
        data_mat = loadmat(file_path)
        hdr = data_mat["hdr"]

        # Extract T0 from original header
        t0_raw = hdr["orig"][0, 0]["T0"][0, 0][0]

        t0_dt = datetime(
            int(t0_raw[0]), int(t0_raw[1]), int(t0_raw[2]),
            int(t0_raw[3]), int(t0_raw[4]), int(t0_raw[5])
        )

        t0_results.append({
            "list_idx": i,
            "file": filename,
            "T0": t0_dt
        })

    except Exception as e:
        errors.append({
            "list_idx": i,
            "file": filename,
            "error": str(e)
        })

df_T0 = pd.DataFrame(t0_results)
df_T0 = df_T0.sort_values("T0").reset_index(drop=True)

print("Successfully processed:", len(df_T0))
print("Errors:", len(errors))

display(df_T0)

Successfully processed: 357
Errors: 0

     list_idx           file                  T0
0           0    ZBJBD_1.mat 2021-01-13 11:40:57
1         111    ZBJBD_2.mat 2021-01-13 17:41:38
2         222    ZBJBD_3.mat 2021-01-13 23:41:38
3         291    ZBJBD_4.mat 2021-01-14 05:41:38
4         302    ZBJBD_5.mat 2021-01-14 11:41:38
..        ...            ...                 ...
352       282  ZBJBD_353.mat 2021-06-22 12:09:50
353       283  ZBJBD_354.mat 2021-06-22 18:11:03
354       284  ZBJBD_355.mat 2021-06-23 00:11:25
355       285  ZBJBD_356.mat 2021-06-23 06:11:25
356       286  ZBJBD_357.mat 2021-06-24 10:35:58

[357 rows x 3 columns]

In [23]:
t0_raw_results = []
errors = []

for i, filename in enumerate(mat_files):
    file_path = folder_path / filename

    try:
        data_mat = loadmat(file_path)
        hdr = data_mat["hdr"]

        # Raw T0 exactly as stored in the .mat structure
        t0_raw = hdr["orig"][0, 0]["T0"][0, 0][0]

        t0_raw_results.append({
            "list_idx": i,
            "file": filename,
            "T0_raw": t0_raw
        })

    except Exception as e:
        errors.append({
            "list_idx": i,
            "file": filename,
            "error": str(e)
        })

df_T0_raw = pd.DataFrame(t0_raw_results)

print("Successfully processed:", len(df_T0_raw))
print("Errors:", len(errors))

display(df_T0_raw)

Successfully processed: 357
Errors: 0

     list_idx           file                     T0_raw
0           0    ZBJBD_1.mat  [2021, 1, 13, 11, 40, 57]
1           1   ZBJBD_10.mat  [2021, 1, 17, 11, 36, 33]
2           2  ZBJBD_100.mat    [2021, 3, 1, 17, 6, 21]
3           3  ZBJBD_101.mat    [2021, 3, 1, 23, 6, 21]
4           4  ZBJBD_102.mat     [2021, 3, 2, 5, 6, 21]
..        ...            ...                        ...
352       352   ZBJBD_95.mat    [2021, 2, 27, 9, 16, 3]
353       353   ZBJBD_96.mat   [2021, 2, 27, 15, 16, 4]
354       354   ZBJBD_97.mat   [2021, 2, 27, 21, 16, 4]
355       355   ZBJBD_98.mat    [2021, 2, 28, 3, 16, 4]
356       356   ZBJBD_99.mat    [2021, 3, 1, 11, 6, 13]

[357 rows x 3 columns]